const express=require('express'),path=require('path'),fs=require('fs'),crypto=require('crypto'),bcrypt=require('bcryptjs'),jwt=require('jsonwebtoken'),multer=require('multer');
const app=express(),PORT=process.env.PORT||3000,SECRET=process.env.JWT_SECRET||'CHANGE_THIS_SECRET';
const DATA=path.join(__dirname,'data/users.json'),UPLOAD=path.join(__dirname,'public/uploads');fs.mkdirSync(UPLOAD,{recursive:true});if(!fs.existsSync(DATA))fs.writeFileSync(DATA,'[]');
app.use(express.json({limit:'2mb'}));app.use(express.static(path.join(__dirname,'public')));
const upload=multer({dest:UPLOAD,limits:{fileSize:50*1024*1024}});
const users=()=>JSON.parse(fs.readFileSync(DATA,'utf8'));const save=u=>fs.writeFileSync(DATA,JSON.stringify(u,null,2));
function auth(req,res,next){let t=(req.headers.authorization||'').replace('Bearer ','');try{req.user=jwt.verify(t,SECRET);next()}catch{return res.status(401).json({error:'Login required.'})}}
app.post('/api/signup',async(req,res)=>{let name=String(req.body.name||'').trim(),email=String(req.body.email||'').trim().toLowerCase(),password=String(req.body.password||'');if(name.length<2)return res.status(400).json({error:'Enter your full name.'});if(!/^\S+@\S+\.\S+$/.test(email))return res.status(400).json({error:'Enter a valid email.'});if(password.length<6)return res.status(400).json({error:'Password must be at least 6 characters.'});let u=users();if(u.some(x=>x.email===email))return res.status(409).json({error:'Account already exists.'});let user={id:crypto.randomUUID(),name,email,passwordHash:await bcrypt.hash(password,12),createdAt:new Date().toISOString()};u.push(user);save(u);let token=jwt.sign({id:user.id,name,email},SECRET,{expiresIn:'7d'});res.json({token,user:{name,email}})});
app.post('/api/login',async(req,res)=>{let email=String(req.body.email||'').trim().toLowerCase(),password=String(req.body.password||''),user=users().find(x=>x.email===email);if(!user||!(await bcrypt.compare(password,user.passwordHash)))return res.status(401).json({error:'Email or password is incorrect.'});let token=jwt.sign({id:user.id,name:user.name,email:user.email},SECRET,{expiresIn:'7d'});res.json({token,user:{name:user.name,email:user.email}})});
app.get('/api/me',auth,(req,res)=>res.json({user:{name:req.user.name,email:req.user.email}}));
function analyze(text){let t=String(text||'').trim().toLowerCase(),flags=[];[['urgent','Urgent wording'],['share this','Pressure to share'],['forward this','Forward/share language'],['100% true','Absolute certainty'],['guaranteed','Guarantee language'],['breaking','Breaking-news style'],['shocking','Sensational wording'],['miracle','Miracle claim']].forEach(([a,b])=>{if(t.includes(a))flags.push(b)});let confidence=Math.max(35,Math.min(96,82-flags.length*7+(t.length>250?4:0)));return{verdict:confidence>=75?'Likely credible':confidence>=55?'Needs verification':'High risk',confidence,summary:'The built-in scanner checks common misinformation/manipulation signals.',signals:flags.length?flags:['No obvious manipulation phrases detected'],disclaimer:'This is a screening tool, not proof of truth. Verify important claims with primary sources.'}}
app.post('/api/scan/text',auth,(req,res)=>{let text=String(req.body.text||'').trim();if(!text)return res.status(400).json({error:'Paste some text first.'});res.json({type:'text',result:analyze(text)})});
app.post('/api/scan/url',auth,async(req,res)=>{let raw=String(req.body.url||'').trim(),u;try{u=new URL(raw);if(!['http:','https:'].includes(u.protocol))throw 0}catch{return res.status(400).json({error:'Enter a valid http/https URL.'})}let host=u.hostname.replace(/^www\./,''),trusted=/(reuters|apnews|bbc|who|un|nasa|thehindu|indianexpress)\./i.test(host)||host.endsWith('.gov.in')||host.endsWith('.nic.in')||host.endsWith('.edu');let title='';try{let r=await fetch(u.href,{headers:{'User-Agent':'Mozilla/5.0 SachDekho'},signal:AbortSignal.timeout(8000)}),h=await r.text();title=((h.match(/<title[^>]*>([\s\S]*?)<\/title>/i)||['',''])[1]||'').replace(/<[^>]+>/g,'').replace(/\s+/g,' ').trim()}catch{}res.json({type:'url',url:u.href,title,result:{verdict:trusted?'Source appears reputable':'Source needs verification',confidence:trusted?86:65,summary:trusted?'The domain matches a recognized source pattern.':'The domain is not on the built-in trusted-source list.',signals:[`Domain: ${host}`,trusted?'Recognized source pattern':'Not in built-in trusted-source list',title?`Page title: ${title}`:'Page title unavailable'],disclaimer:'Domain reputation alone does not prove an individual claim is true.'}})});
app.post('/api/scan/file',auth,upload.single('file'),(req,res)=>{if(!req.file)return res.status(400).json({error:'Choose an image or video.'});let ok=req.file.mimetype.startsWith('image/')||req.file.mimetype.startsWith('video/');if(!ok){try{fs.unlinkSync(req.file.path)}catch{}return res.status(400).json({error:'Only image/video files are supported.'})}res.json({type:req.file.mimetype.startsWith('image/')?'image':'video',result:{verdict:'Needs verification',confidence:60,summary:'The file was received successfully. Production-grade frame/deepfake analysis needs a specialist vision model.',signals:[`Type: ${req.file.mimetype}`,`Size: ${(req.file.size/1048576).toFixed(2)} MB`],disclaimer:'File reception is working, but this built-in version does not claim to prove authenticity.'}})});
app.get('/api/search',auth,async(req,res)=>{let q=String(req.query.q||'').trim();if(!q)return res.status(400).json({error:'Type something to search.'});try{let r=await fetch('https://api.duckduckgo.com/?q='+encodeURIComponent(q)+'&format=json&no_html=1&skip_disambig=1'),d=await r.json();let topics=(d.RelatedTopics||[]).flatMap(x=>x.Topics||[x]).filter(x=>x.Text&&x.FirstURL).slice(0,8).map(x=>({title:x.Text,url:x.FirstURL}));res.json({answer:d.AbstractText||'',source:d.AbstractSource||'',sourceUrl:d.AbstractURL||'',topics})}catch{res.status(502).json({error:'Search service temporarily unavailable.'})}});
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public/index.html')));app.listen(PORT,()=>console.log('Sach Dekho: http://localhost:'+PORT));
